name: AVL_Tree commit checker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install google test and boost, also install g++-12 (for atomic shared pointers)
      run: sudo apt-get install libgtest-dev libgmock-dev libboost-dev g++-12
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: CMake release config
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=Release
    - name: CMake release build
      run: cmake --build build
    - name: CMake release test
      run: env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
